# Generated by Django 3.1.1 on 2021-01-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ImageField(upload_to='uploads')),
                ('form_factor', models.FloatField(blank=True, null=True)),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('rect', models.FloatField(blank=True, null=True)),
                ('narrow_factor', models.FloatField(blank=True, null=True)),
                ('prd', models.FloatField(blank=True, null=True)),
                ('plw', models.FloatField(blank=True, null=True)),
                ('mean_h', models.FloatField(blank=True, null=True)),
                ('mean_s', models.FloatField(blank=True, null=True)),
                ('mean_v', models.FloatField(blank=True, null=True)),
                ('kelas', models.IntegerField(blank=True, choices=[(0, 'MALACCENSIS'), (1, 'SUBINTEGRA')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='models')),
                ('datalatih_ids', models.TextField(blank=True, null=True)),
                ('datauji_ids', models.TextField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('epoch', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
